# Generated by Django 4.1.7 on 2023-03-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='deadline',
        ),
    ]
