# Generated by Django 4.1.7 on 2023-03-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todotask_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
